default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: 123456
  host: localhost
  port: 5432

development:
  <<: *default
  database: customer_loan_database_development2

test:
  <<: *default
 url: <%= ENV['DATABASE_URL'] %>
 
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
